# Build workflow does the following:
#   - checkout all files
#   - get the latest version number
#   - setup python 3.x env
#   - install python dependencies
#   - build python distributions
#   - create a tag and release
#   - upload assets to the release
#   - upload assets to pypi

name: Build

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build_and_test:
    runs-on: [self-hosted, Linux, Ubuntu, x64]
    strategy:
      matrix:
        python-version: [python27, python38]
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set python path
      id: path
      run: echo "::set-output name=pythonv::/home/otg/${{matrix.python-version}}/bin/python"

    - name: Install dependencies
      run: |
        ${{steps.path.outputs.pythonv}} -m pip install --upgrade -r requirements.txt

    - name: Build distributions
      run: |
        ${{steps.path.outputs.pythonv}} setup.py sdist --formats=gztar bdist_wheel --universal

    - name: Get VERSION number
      id: get_version
      run: echo "::set-output name=version::$(cat VERSION)"
    
    - name: Test whl distribution installation
      run: |
        ${{steps.path.outputs.pythonv}} -m pip install --upgrade dist/snappi_ixnetwork-${{ steps.get_version.outputs.version }}-py2.py3-none-any.whl[dev]

#    - name: Run tests
#      run: |
#        ${{steps.path.outputs.pythonv}} -m pytest --api_server="https://10.39.71.97:443" --ports="10.39.65.230;6;1 10.39.65.230;6;2 10.39.65.230;6;3 10.39.65.230;6;4" --media="fiber" tests -m "not e2e and not l1_manual"

  create_release_and_deploy:
    needs: build_and_test
    runs-on: [self-hosted, Linux, Ubuntu, x64]
    if: github.event_name == 'push'
    steps:
    - name: Get all changes
      id: file_changes
      uses: jitterbit/get-changed-files@v1
      with:
          format: 'json'

    - name: Output changed files
      id: changed_files
      run: echo ${{steps.file_changes.outputs.modified}}

    - name: Create Release
      if: true == contains(steps.file_changes.outputs.modified, 'VERSION')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: v${{ needs.build_and_test.outputs.version }}
        release_name: Release ${{ needs.build_and_test.outputs.version  }}
        draft: false
        prerelease: false

    - name: Upload Assets To Release
      if: true == contains(steps.file_changes.outputs.modified, 'VERSION')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: v${{ needs.build_and_test.outputs.version }}
        overwrite: true
        file_glob: true   
        
    - name: Upload Assets to Pypi
      if: true == contains(steps.file_changes.outputs.modified, 'VERSION')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        /home/otg/python38/bin/python -m twine upload dist/snappi_ixnetwork-${{ needs.build_and_test.outputs.version  }}-py2.py3-none-any.whl
        /home/otg/python38/bin/python -m twine upload dist/snappi_ixnetwork-${{ needs.build_and_test.outputs.version  }}.tar.gz
